# Generated by Django 2.2.19 on 2023-03-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(max_length=200)),
                ('link_url', models.TextField()),
            ],
            options={
                'verbose_name': 'Полезные ссылки',
            },
        ),
    ]
