# Generated by Django 2.2.19 on 2023-03-08 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'verbose_name': 'Полезная ссылка', 'verbose_name_plural': 'Полезные ссылки'},
        ),
    ]
