# Generated by Django 2.2.19 on 2023-03-13 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20230313_1447'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostFile',
        ),
    ]
